# Configuration for strategy optimization
symbols:
  - AAPL
  - MSFT
  - GOOGL

data:
  period: "3mo"
  interval: "1d"

strategies:
  builtin:
    - default

strategy_params:
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  rsi_period: 14
  roc_period: 5
  ema_mom_period: 20

output:
  mode: "comparison"
  save_results: true
  results_file: "optimization_results.json"
