# Simple configuration for quick testing
symbols:
  - AAPL
  - TSLA

data:
  period: "30d"
  interval: "15m"

strategies:
  builtin:
    - default
    - trend_following
    - macd_crossover

output:
  mode: "comparison"
