# Advanced configuration for strategy optimization
# This config demonstrates optimization with multiple symbols and longer time periods

symbols:
  - AAPL
  - MSFT
  - GOOGL
  - TSLA
  - AMZN

data:
  period: "6mo"  # Longer period for more robust optimization
  interval: "1d"

strategies:
  builtin:
    - default
    - trend_following
    - mean_reversion
    - macd_crossover

strategy_params:
  # Default parameters (will be optimized)
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  rsi_period: 14
  roc_period: 5
  ema_mom_period: 20

output:
  mode: "comparison"
  save_results: true
  results_file: "advanced_optimization_results.json"
